name: Build
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.9
    - name: Build with Maven
      run: mvn compile -V -B
    - name: Test with Maven
      run: mvn verify -V -B
